<Workspace Version="1.3.1.1736" X="-126.24841875" Y="173.736741779158" zoom="1.33823125" ScaleFactor="1" Name="TestTwo_Faraday" Description="The second test node for Faraday" ID="86d21c00-2595-4608-8e1a-29d0fc5a50f2" Category="Faraday">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="ab0f27c4-d393-4b66-aea4-7f321032ed2c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

#Assign your output to the OUT variable.
OUT = 0</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="39b5b16c-5961-432d-88e8-f380bcae3612" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="OUT" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ab0f27c4-d393-4b66-aea4-7f321032ed2c" start_index="0" end="39b5b16c-5961-432d-88e8-f380bcae3612" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>